In [38]:
import json
import pandas as pd
import numpy as np

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [39]:
test_folder_path = Path("./tests")
test = "spectra"

In [40]:
with open(test_folder_path / test / f"{test}_specs.json" ) as f:
    test_specs = json.load(f)

norms_path = test_folder_path / test / f"{test}_norms_ita.csv"
norms = pd.read_csv(norms_path)

In [41]:
def convert_to_matrices(test_specs):
    # get test length
    test_length = test_specs["length"]
    # init matrices to be returned
    df_straight = pd.DataFrame()
    df_reversed = pd.DataFrame()
    # iterate over scales
    for scale in test_specs["scales"]:
        # get scale label, straight and reversed items
        scale_label, straight_items_indices, reversed_items_indices = scale
        # iterate over type of items (either straight or reversed)
        for df, items_indices in [(df_straight, straight_items_indices), (df_reversed, reversed_items_indices)]:
            # init new series with zeroes 
            zeros = pd.Series(np.zeros(test_length))
            # correct items indices, since items are 1-based while matrix indices are 0-based
            matrix_indices = pd.Series(items_indices).sub(1)
            # "switch to 1" scale items in zeros series
            zeros[matrix_indices] = 1
            # add scale items matrix to df
            df[scale_label] = zeros
    return df_straight, df_reversed

def compute_raw_scores(data, test_specs, score_strategy = "sum", split_results = False):
    
    # init results
    results = pd.DataFrame()
    # clone data
    answers = data.copy()
    # get scales items matrices (two separate matrices for straight and reversed items)
    df_straight, df_reversed = convert_to_matrices(test_specs)
    
    ############################################################
    # straight items
    ############################################################
    
    # compute sum of straight items
    score_straight_sum = np.dot(answers.fillna(0), df_straight)
    # compute mean of straight items
    with np.errstate(divide='ignore', invalid='ignore'):
        score_straight_mean = np.true_divide(score_straight_sum, df_straight.sum(axis=0).to_numpy())
        score_straight_mean[score_straight_mean == np.inf] = 0
        score_straight_mean = np.nan_to_num(score_straight_mean)

    ############################################################
    # reversed items
    ############################################################
    
    # compute amount to use for reversed items
    rev = test_specs["likert"]["min"] + test_specs["likert"]["max"]
    # compute sum of reversed items
    score_reversed_sum = np.dot(rev - answers.fillna(rev), df_reversed)
    # compute mean of reversed items
    with np.errstate(divide='ignore', invalid='ignore'):
        score_reversed_mean = np.true_divide(score_reversed_sum, df_reversed.sum(axis=0).to_numpy())
        score_reversed_mean[score_reversed_mean == np.inf] = 0
        score_reversed_mean = np.nan_to_num(score_reversed_mean)

    #############################################################
    # final results
    ############################################################

    # if we want results splitted by straight/reversed items
    if split_results:
        return score_straight_sum, score_reversed_sum
    # otherwise return combined results
    else:
        # compute final results
        results.loc[:, df_straight.columns] = score_straight_sum + score_reversed_sum
        if score_strategy == "mean":
            results.loc[:, df_straight.columns] = score_straight_mean + score_reversed_mean
        
        # return results
        return results.astype(int)

def count_items_per_scale(data, test_specs, split_results = False):
    # init results
    results = pd.DataFrame()
    # clone data
    answers = data.copy()
    # get scales items matrices (two separate matrices for straight and reversed items)
    df_straight, df_reversed = convert_to_matrices(test_specs)
    # merge straight and reversed items matrices
    df_tot = df_straight + df_reversed
    # if we want results splitted by straight/reversed items
    if split_results:
        return df_straight.sum(), df_reversed.sum()
    # otherwise return combined results
    return df_tot.sum()

def count_missing_items_per_scale(data, test_specs, split_results = False):
    # init results
    results = pd.DataFrame()
    # clone data
    answers = data.copy()
    # get scales items matrices (two separate matrices for straight and reversed items)
    df_straight, df_reversed = convert_to_matrices(test_specs)
    # merge straight and reversed items matrices
    df_tot = df_straight + df_reversed
    # if we want results splitted by straight/reversed items
    if split_results:
        return (
            df_straight.apply(lambda x: answers.T.loc[x.astype(bool).values].isna().sum()),
            df_reversed.apply(lambda x: answers.T.loc[x.astype(bool).values].isna().sum())
        )
    # otherwise return combined results
    return df_tot.apply(lambda x: answers.T.loc[x.astype(bool).values].isna().sum())

def compute_raw_scores_compensate_for_missing_items(data, test_specs):
    
    # get splitted data that is needed for computing raw scores while compensating for missing items
    score_straight, score_reversed = compute_raw_scores(data, test_specs, score_strategy = "sum", split_results = True)
    missing_straight, missing_reversed = count_missing_items_per_scale(data, test_specs, split_results = True)
    items_straight, items_reversed = count_items_per_scale(data, test_specs, split_results = True)
    # init list
    components = []
    # compute corrected raw scores 
    for raw_scores, missing_items_by_scale, items_by_scale in [
        (score_straight, missing_straight, items_straight),
        (score_reversed, missing_reversed, items_reversed)
    ]: 
        # compute how many items where effectively responded (by scale)
        items_with_answers_by_scale = items_by_scale - missing_items_by_scale
        with np.errstate(divide='ignore', invalid='ignore'):
            # compute mean responses (by scale)
            mean_results= np.true_divide(raw_scores, items_with_answers_by_scale.astype(int))
            mean_results[mean_results == np.inf] = 0
            mean_results = np.nan_to_num(mean_results)
            # compute corrected results (by scale)
            corrected_results = mean_results * items_by_scale.to_numpy().T
            components.append(corrected_results)
    # return results as a pandas DataFrame
    return pd.DataFrame(components[0] + components[1], index=data.index, columns=items_straight.index).astype(int)
    
def compute_standard_score(s, **kwargs):
    # get kwargs
    norms, type = kwargs["norms"],  kwargs["type"]
    # return standard scores
    return norms[norms["scale"].eq(s.name)].take(s)[type].values

In [42]:
# load data
data = pd.read_csv("data_spectra.csv")
data.head()

,i1,i2,i3,i4,i5,i6,i7,i8,i9,i10,i11,i12,i13,i14,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24,i25,i26,i27,i28,i29,i30,i31,i32,i33,i34,i35,i36,i37,i38,i39,i40,i41,i42,i43,i44,i45,i46,i47,i48,i49,i50,i51,i52,i53,i54,i55,i56,i57,i58,i59,i60,i61,i62,i63,i64,i65,i66,i67,i68,i69,i70,i71,i72,i73,i74,i75,i76,i77,i78,i79,i80,i81,i82,i83,i84,i85,i86,i87,i88,i89,i90,i91,i92,i93,i94,i95,i96
0,4,3,2,1,3,1,1,1,2,1,1,1,2,1,1,1,1,4,3,3,2,3,1,2,1,1,1,1,3,1,1,1,5,5,2,3,1,3,1,1,1,1,1,1,1,5,1,1,5,1,5,3,3,1,4,1,1,2,1,1,1,1,5,1,2,2,3,3,3,4,1,1,2,1,1,1,3,1,1,1,3,3,4,1,2,1,1,1,2,4,1,4,3,1,2,1

In [43]:
items_by_scale = count_items_per_scale(data, test_specs)
items_by_scale

dep      6.0
anx      8.0
soc      5.0
pts      6.0
alc      6.0
agg      6.0
anti     8.0
drg      6.0
psy      6.0
par      6.0
man      5.0
gra      6.0
cog      5.0
pf       8.0
sui      6.0
int     25.0
ext     26.0
ri      23.0
gpi     74.0
dtype: float64

In [44]:
missing_items_by_scale = count_missing_items_per_scale(data, test_specs)
missing_items_by_scale

,dep,anx,soc,pts,alc,agg,anti,drg,psy,par,man,gra,cog,pf,sui,int,ext,ri,gpi
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [45]:
raw_scores = compute_raw_scores(data, test_specs)
raw_scores

,dep,anx,soc,pts,alc,agg,anti,drg,psy,par,man,gra,cog,pf,sui,int,ext,ri,gpi
0,23,22,14,21,8,8,10,6,6,7,6,7,5,32,6,80,32,26,138

In [46]:
raw_scores_corrected = compute_raw_scores_compensate_for_missing_items(data, test_specs)
raw_scores_corrected

,dep,anx,soc,pts,alc,agg,anti,drg,psy,par,man,gra,cog,pf,sui,int,ext,ri,gpi
0,23,22,14,21,8,8,10,6,6,7,6,7,5,32,6,80,32,25,138

In [47]:
t_scores = raw_scores.apply(compute_standard_score, norms=norms, type="tscore")
t_scores

,dep,anx,soc,pts,alc,agg,anti,drg,psy,par,man,gra,cog,pf,sui,int,ext,ri,gpi
0,89,63,63,67,55,45,46,48,44,48,45,44,39,51,46,74,56,44,65

In [117]:
df = pd.read_clipboard()

In [132]:
l = df.melt(id_vars=["raw1","raw2","raw3","raw4","raw5"])
m = l["value"]
m.index = range(74,374)
m = m.dropna()
m

74      36.0
75      36.0
76      37.0
77      37.0
78      38.0
79      38.0
80      38.0
81      39.0
82      39.0
83      40.0
84      40.0
85      40.0
86      41.0
87      41.0
88      42.0
89      42.0
90      43.0
91      43.0
92      43.0
93      44.0
94      44.0
95      45.0
96      45.0
97      45.0
98      46.0
99      46.0
100     47.0
101     47.0
102     47.0
103     48.0
104     48.0
105     49.0
106     49.0
107     50.0
108     50.0
109     50.0
110     51.0
111     51.0
112     52.0
113     52.0
114     52.0
115     53.0
116     53.0
117     54.0
118     54.0
119     54.0
120     55.0
121     55.0
122     56.0
123     56.0
124     57.0
125     57.0
126     57.0
127     58.0
128     58.0
129     59.0
130     59.0
131     59.0
132     60.0
133     60.0
134     61.0
135     61.0
136     61.0
137     62.0
138     62.0
139     63.0
140     63.0
141     63.0
142     64.0
143     64.0
144     65.0
145     65.0
146     66.0
147     66.0
148     66.0
149     67.0
150     67.0
151     68.0
152     68.0
153     68.0
154     69.0
155     69.0
156     70.0
157     70.0
158     70.0
159     71.0
160     71.0
161     72.0
162     72.0
163     73.0
164     73.0
165     73.0
166     74.0
167     74.0
168     75.0
169     75.0
170     75.0
171     76.0
172     76.0
173     77.0
174     77.0
175     77.0
176     78.0
177     78.0
178     79.0
179     79.0
180     80.0
181     80.0
182     80.0
183     81.0
184     81.0
185     82.0
186     82.0
187     82.0
188     83.0
189     83.0
190     84.0
191     84.0
192     84.0
193     85.0
194     85.0
195     86.0
196     86.0
197     87.0
198     87.0
199     87.0
200     88.0
201     88.0
202     89.0
203     89.0
204     89.0
205     90.0
206     90.0
207     91.0
208     91.0
209     91.0
210     92.0
211     92.0
212     93.0
213     93.0
214     94.0
215     94.0
216     94.0
217     95.0
218     95.0
219     96.0
220     96.0
221     96.0
222     97.0
223     97.0
224     98.0
225     98.0
226     98.0
227     99.0
228     99.0
229    100.0
230    100.0
231    101.0
232    101.0
233    101.0
234    102.0
235    102.0
236    103.0
237    103.0
238    103.0
239    104.0
240    104.0
241    105.0
242    105.0
243    105.0
244    106.0
245    106.0
246    107.0
247    107.0
248    108.0
249    108.0
250    108.0
251    109.0
252    109.0
253    110.0
254    110.0
255    110.0
256    111.0
257    111.0
258    112.0
259    112.0
260    112.0
261    113.0
262    113.0
263    114.0
264    114.0
265    114.0
266    115.0
267    115.0
268    116.0
269    116.0
270    117.0
271    117.0
272    117.0
273    118.0
274    118.0
275    119.0
276    119.0
277    119.0
278    120.0
279    120.0
280    121.0
281    121.0
282    121.0
283    122.0
284    122.0
285    123.0
286    123.0
287    124.0
288    124.0
289    124.0
290    125.0
291    125.0
292    126.0
293    126.0
294    126.0
295    127.0
296    127.0
297    128.0
298    128.0
299    128.0
300    129.0
301    129.0
302    130.0
303    130.0
304    131.0
305    131.0
306    131.0
307    132.0
308    132.0
309    133.0
310    133.0
311    133.0
312    134.0
313    134.0
314    135.0
315    135.0
316    135.0
317    136.0
318    136.0
319    137.0
320    137.0
321    138.0
322    138.0
323    138.0
324    139.0
325    139.0
326    140.0
327    140.0
328    140.0
329    141.0
330    141.0
331    142.0
332    142.0
333    142.0
334    143.0
335    143.0
336    144.0
337    144.0
338    145.0
339    145.0
340    145.0
341    146.0
342    146.0
343    147.0
344    147.0
345    147.0
346    148.0
347    148.0
348    149.0
349    149.0
350    149.0
351    150.0
352    150.0
353    151.0
354    151.0
355    152.0
356    152.0
357    152.0
358    153.0
359    153.0
360    154.0
361    154.0
362    154.0
363    155.0
364    155.0
365    156.0
366    156.0
367    156.0
368    157.0
369    157.0
370    158.0
Name: value, dtype: float64

In [139]:
m = pd.concat([
    pd.Series([ 36 for i in range(0,74)], name="gpi"),
    m
]).to_frame().reset_index().rename(columns={ "index": "raw", 0: "tscore"}) # .melt(id_vars="index").loc[:, ["variable", "index", "value"]]

In [142]:
m["scale"] = "gpi"
m

     raw  tscore scale
0      0    36.0   gpi
1      1    36.0   gpi
2      2    36.0   gpi
3      3    36.0   gpi
4      4    36.0   gpi
5      5    36.0   gpi
6      6    36.0   gpi
7      7    36.0   gpi
8      8    36.0   gpi
9      9    36.0   gpi
10    10    36.0   gpi
11    11    36.0   gpi
12    12    36.0   gpi
13    13    36.0   gpi
14    14    36.0   gpi
15    15    36.0   gpi
16    16    36.0   gpi
17    17    36.0   gpi
18    18    36.0   gpi
19    19    36.0   gpi
20    20    36.0   gpi
21    21    36.0   gpi
22    22    36.0   gpi
23    23    36.0   gpi
24    24    36.0   gpi
25    25    36.0   gpi
26    26    36.0   gpi
27    27    36.0   gpi
28    28    36.0   gpi
29    29    36.0   gpi
30    30    36.0   gpi
31    31    36.0   gpi
32    32    36.0   gpi
33    33    36.0   gpi
34    34    36.0   gpi
35    35    36.0   gpi
36    36    36.0   gpi
37    37    36.0   gpi
38    38    36.0   gpi
39    39    36.0   gpi
40    40    36.0   gpi
41    41    36.0   gpi
42    42    36.0   gpi
43    43    36.0   gpi
44    44    36.0   gpi
45    45    36.0   gpi
46    46    36.0   gpi
47    47    36.0   gpi
48    48    36.0   gpi
49    49    36.0   gpi
50    50    36.0   gpi
51    51    36.0   gpi
52    52    36.0   gpi
53    53    36.0   gpi
54    54    36.0   gpi
55    55    36.0   gpi
56    56    36.0   gpi
57    57    36.0   gpi
58    58    36.0   gpi
59    59    36.0   gpi
60    60    36.0   gpi
61    61    36.0   gpi
62    62    36.0   gpi
63    63    36.0   gpi
64    64    36.0   gpi
65    65    36.0   gpi
66    66    36.0   gpi
67    67    36.0   gpi
68    68    36.0   gpi
69    69    36.0   gpi
70    70    36.0   gpi
71    71    36.0   gpi
72    72    36.0   gpi
73    73    36.0   gpi
74    74    36.0   gpi
75    75    36.0   gpi
76    76    37.0   gpi
77    77    37.0   gpi
78    78    38.0   gpi
79    79    38.0   gpi
80    80    38.0   gpi
81    81    39.0   gpi
82    82    39.0   gpi
83    83    40.0   gpi
84    84    40.0   gpi
85    85    40.0   gpi
86    86    41.0   gpi
87    87    41.0   gpi
88    88    42.0   gpi
89    89    42.0   gpi
90    90    43.0   gpi
91    91    43.0   gpi
92    92    43.0   gpi
93    93    44.0   gpi
94    94    44.0   gpi
95    95    45.0   gpi
96    96    45.0   gpi
97    97    45.0   gpi
98    98    46.0   gpi
99    99    46.0   gpi
100  100    47.0   gpi
101  101    47.0   gpi
102  102    47.0   gpi
103  103    48.0   gpi
104  104    48.0   gpi
105  105    49.0   gpi
106  106    49.0   gpi
107  107    50.0   gpi
108  108    50.0   gpi
109  109    50.0   gpi
110  110    51.0   gpi
111  111    51.0   gpi
112  112    52.0   gpi
113  113    52.0   gpi
114  114    52.0   gpi
115  115    53.0   gpi
116  116    53.0   gpi
117  117    54.0   gpi
118  118    54.0   gpi
119  119    54.0   gpi
120  120    55.0   gpi
121  121    55.0   gpi
122  122    56.0   gpi
123  123    56.0   gpi
124  124    57.0   gpi
125  125    57.0   gpi
126  126    57.0   gpi
127  127    58.0   gpi
128  128    58.0   gpi
129  129    59.0   gpi
130  130    59.0   gpi
131  131    59.0   gpi
132  132    60.0   gpi
133  133    60.0   gpi
134  134    61.0   gpi
135  135    61.0   gpi
136  136    61.0   gpi
137  137    62.0   gpi
138  138    62.0   gpi
139  139    63.0   gpi
140  140    63.0   gpi
141  141    63.0   gpi
142  142    64.0   gpi
143  143    64.0   gpi
144  144    65.0   gpi
145  145    65.0   gpi
146  146    66.0   gpi
147  147    66.0   gpi
148  148    66.0   gpi
149  149    67.0   gpi
150  150    67.0   gpi
151  151    68.0   gpi
152  152    68.0   gpi
153  153    68.0   gpi
154  154    69.0   gpi
155  155    69.0   gpi
156  156    70.0   gpi
157  157    70.0   gpi
158  158    70.0   gpi
159  159    71.0   gpi
160  160    71.0   gpi
161  161    72.0   gpi
162  162    72.0   gpi
163  163    73.0   gpi
164  164    73.0   gpi
165  165    73.0   gpi
166  166    74.0   gpi
167  167    74.0   gpi
168  168    75.0   gpi
169  169    75.0   gpi
170  170    75.0   gpi
171  171    76.0   gpi
172  172    76.0   gpi
173  173    77.0   gpi
174  174    77.0   gpi
175  175    77.0   gpi
176  176    78.0   gpi
177  177    78.0   gpi
178  178    79.0   gpi
179  179    79.0   gpi
180  180    80.0   gpi
181  181    80.0   gpi
182  182    80.0   gpi
183  183    81.0   gpi
184  184    81.0   gpi
185  185    82.0   gpi
186  186    82.0   gpi
187  187    82.0   gpi
188  188    83.0   gpi
189  189    83.0   gpi
190  190    84.0   gpi
191  191    84.0   gpi
192  192    84.0   gpi
193  193    85.0   gpi
194  194    85.0   gpi
195  195    86.0   gpi
196  196    86.0   gpi
197  197    87.0   gpi
198  198    87.0   gpi
199  199    87.0   gpi
200  200    88.0   gpi
201  201    88.0   gpi
202  202    89.0   gpi
203  203    89.0   gpi
204  204    89.0   gpi
205  205    90.0   gpi
206  206    90.0   gpi
207  207    91.0   gpi
208  208    91.0   gpi
209  209    91.0   gpi
210  210    92.0   gpi
211  211    92.0   gpi
212  212    93.0   gpi
213  213    93.0   gpi
214  214    94.0   gpi
215  215    94.0   gpi
216  216    94.0   gpi
217  217    95.0   gpi
218  218    95.0   gpi
219  219    96.0   gpi
220  220    96.0   gpi
221  221    96.0   gpi
222  222    97.0   gpi
223  223    97.0   gpi
224  224    98.0   gpi
225  225    98.0   gpi
226  226    98.0   gpi
227  227    99.0   gpi
228  228    99.0   gpi
229  229   100.0   gpi
230  230   100.0   gpi
231  231   101.0   gpi
232  232   101.0   gpi
233  233   101.0   gpi
234  234   102.0   gpi
235  235   102.0   gpi
236  236   103.0   gpi
237  237   103.0   gpi
238  238   103.0   gpi
239  239   104.0   gpi
240  240   104.0   gpi
241  241   105.0   gpi
242  242   105.0   gpi
243  243   105.0   gpi
244  244   106.0   gpi
245  245   106.0   gpi
246  246   107.0   gpi
247  247   107.0   gpi
248  248   108.0   gpi
249  249   108.0   gpi
250  250   108.0   gpi
251  251   109.0   gpi
252  252   109.0   gpi
253  253   110.0   gpi
254  254   110.0   gpi
255  255   110.0   gpi
256  256   111.0   gpi
257  257   111.0   gpi
258  258   112.0   gpi
259  259   112.0   gpi
260  260   112.0   gpi
261  261   113.0   gpi
262  262   113.0   gpi
263  263   114.0   gpi
264  264   114.0   gpi
265  265   114.0   gpi
266  266   115.0   gpi
267  267   115.0   gpi
268  268   116.0   gpi
269  269   116.0   gpi
270  270   117.0   gpi
271  271   117.0   gpi
272  272   117.0   gpi
273  273   118.0   gpi
274  274   118.0   gpi
275  275   119.0   gpi
276  276   119.0   gpi
277  277   119.0   gpi
278  278   120.0   gpi
279  279   120.0   gpi
280  280   121.0   gpi
281  281   121.0   gpi
282  282   121.0   gpi
283  283   122.0   gpi
284  284   122.0   gpi
285  285   123.0   gpi
286  286   123.0   gpi
287  287   124.0   gpi
288  288   124.0   gpi
289  289   124.0   gpi
290  290   125.0   gpi
291  291   125.0   gpi
292  292   126.0   gpi
293  293   126.0   gpi
294  294   126.0   gpi
295  295   127.0   gpi
296  296   127.0   gpi
297  297   128.0   gpi
298  298   128.0   gpi
299  299   128.0   gpi
300  300   129.0   gpi
301  301   129.0   gpi
302  302   130.0   gpi
303  303   130.0   gpi
304  304   131.0   gpi
305  305   131.0   gpi
306  306   131.0   gpi
307  307   132.0   gpi
308  308   132.0   gpi
309  309   133.0   gpi
310  310   133.0   gpi
311  311   133.0   gpi
312  312   134.0   gpi
313  313   134.0   gpi
314  314   135.0   gpi
315  315   135.0   gpi
316  316   135.0   gpi
317  317   136.0   gpi
318  318   136.0   gpi
319  319   137.0   gpi
320  320   137.0   gpi
321  321   138.0   gpi
322  322   138.0   gpi
323  323   138.0   gpi
324  324   139.0   gpi
325  325   139.0   gpi
326  326   140.0   gpi
327  327   140.0   gpi
328  328   140.0   gpi
329  329   141.0   gpi
330  330   141.0   gpi
331  331   142.0   gpi
332  332   142.0   gpi
333  333   142.0   gpi
334  334   143.0   gpi
335  335   143.0   gpi
336  336   144.0   gpi
337  337   144.0   gpi
338  338   145.0   gpi
339  339   145.0   gpi
340  340   145.0   gpi
341  341   146.0   gpi
342  342   146.0   gpi
343  343   147.0   gpi
344  344   147.0   gpi
345  345   147.0   gpi
346  346   148.0   gpi
347  347   148.0   gpi
348  348   149.0   gpi
349  349   149.0   gpi
350  350   149.0   gpi
351  351   150.0   gpi
352  352   150.0   gpi
353  353   151.0   gpi
354  354   151.0   gpi
355  355   152.0   gpi
356  356   152.0   gpi
357  357   152.0   gpi
358  358   153.0   gpi
359  359   153.0   gpi
360  360   154.0   gpi
361  361   154.0   gpi
362  362   154.0   gpi
363  363   155.0   gpi
364  364   155.0   gpi
365  365   156.0   gpi
366  366   156.0   gpi
367  367   156.0   gpi
368  368   157.0   gpi
369  369   157.0   gpi
370  370   158.0   gpi