In [1]:
import pandas as pd
import numpy as np

In [7]:
def convert_to_matrices(test):
    test_length = test["length"]
    df_straight = pd.DataFrame()
    df_reversed = pd.DataFrame()
    for scale in test["scales"]:
        scale_label, straight, reversed = scale
        zeros = pd.Series(np.zeros(test_length))
        indices = pd.Series(straight).sub(1)
        zeros[indices] = 1
        df_straight[scale_label] = zeros
        zeros = pd.Series(np.zeros(test_length))
        indices = pd.Series(reversed).sub(1)
        zeros[indices] = 1
        df_reversed[scale_label] = zeros
    return (df_straight, df_reversed)

In [8]:
test = {
    "name": "Test 1",
    "length": 12,
    "likert": {
        "min": 1,
        "max": 5
    },
   "scales" : [
        ("Scala 1", (2), (3,4)),
        ("Scala 2", (6,7,8), (9,10)),
    ]
}

In [9]:
data = pd.DataFrame({
    "i1": [np.NaN,2,3,4,5],
    "i2": [3,2,3,4,5],
    "i3": [1,2,3,4,5],
    "i4": [1,2,3,4,5],
    "i5": [np.NaN,2,3,4,5],
    "i6": [3,2,3,4,5],
    "i7": [3,2,3,4,5],
    "i8": [2,2,3,4,5],
    "i9": [1,2,3,4,5],
    "i10": [1,2,3,4,5],
    "i11": [1,2,3,4,5],
    "i12": [1,2,3,4,5],
})

data

    i1  i2  i3  i4   i5  i6  i7  i8  i9  i10  i11  i12
0  NaN   3   1   1  NaN   3   3   2   1    1    1    1
1  2.0   2   2   2  2.0   2   2   2   2    2    2    2
2  3.0   3   3   3  3.0   3   3   3   3    3    3    3
3  4.0   4   4   4  4.0   4   4   4   4    4    4    4
4  5.0   5   5   5  5.0   5   5   5   5    5    5    5

In [14]:
def compute_raw_scores(data, test):
    # clone data
    answers = data.copy()
    # get scales items matrices (two separate matrices for straight items and reversed items)
    df_straight, df_reversed = convert_to_matrices(test)
    # compute sum of straight items
    score_straight = np.dot(answers.fillna(0), df_straight)
    # compute amount to use for reversed items
    rev = test["likert"]["min"] + test["likert"]["max"]
    # compute sum of reversed items
    score_reversed = np.dot(rev - answers.fillna(rev), df_reversed)
    # compute score
    results.loc[:, df_straight.columns] = score_straight + score_reversed
    # return results
    return results

In [15]:
compute_raw_scores(data, test)

    i1  i2  i3  i4   i5  i6  i7  i8  i9  i10  i11  i12  Scala 1  Scala 2
0  NaN   3   1   1  NaN   3   3   2   1    1    1    1     13.0     18.0
1  2.0   2   2   2  2.0   2   2   2   2    2    2    2     10.0     14.0
2  3.0   3   3   3  3.0   3   3   3   3    3    3    3      9.0     15.0
3  4.0   4   4   4  4.0   4   4   4   4    4    4    4      8.0     16.0
4  5.0   5   5   5  5.0   5   5   5   5    5    5    5      7.0     17.0